<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_680b8424acb32',
    'title' => __('Västsverige', 'event-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_680b8424b1c92',
            'label' => __('Daglig import', 'event-manager'),
            'name' => 'vastsverige_daily_cron',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
        1 => array(
            'key' => 'field_680b8424b1c99',
            'label' => __('Poststatus', 'event-manager'),
            'name' => 'vastsverige_post_status',
            'aria-label' => '',
            'type' => 'radio',
            'instructions' => __('Välj status för importerade evenemang.', 'event-manager'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'draft' => __('Utkast', 'event-manager'),
                'publish' => __('Publicerad', 'event-manager'),
            ),
            'default_value' => __('draft', 'event-manager'),
            'return_format' => 'value',
            'allow_null' => 0,
            'other_choice' => 0,
            'layout' => 'vertical',
            'save_other_choice' => 0,
        ),
        2 => array(
            'key' => 'field_680b8424b1ca0',
            'label' => __('API-länkar', 'event-manager'),
            'name' => 'vastsverige_api_urls',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => __('Lägg till API länkar för import från Open Library Solutions.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'block',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => __('Lägg till rad', 'event-manager'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_680b8424b4e22',
                    'label' => __('API-länk', 'event-manager'),
                    'name' => 'vastsverige_api_url',
                    'aria-label' => '',
                    'type' => 'url',
                    'instructions' => __('API-URL inklusive evenemangs-endpoint, utan frågesträng. T.ex. “https://example.com/api/events”.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'parent_repeater' => 'field_680b8424b1ca0',
                ),
                1 => array(
                    'key' => 'field_680b8424b4e29',
                    'label' => __('Konfiguration', 'event-manager'),
                    'name' => 'vastsverige_api_config',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => __('Välj vilken konfiguration du vill hämta data ifrån. Varje kommun har en egen konfiguration. T ex Alingsås Kommun har 2671', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_680b8424b1ca0',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options-options',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}